### ISSUE TITLE
Error when 'arr is has authentication enabled

### ISSUE THREAD

**Issue by tigattack** [Flemmarr/Flemmarr#13]
When an 'arr app has authentication enabled, Flemmarr cannot apply the config and exits with the following error:

```
Trying to connect to sonarr
Traceback (most recent call last):
  File "//run.py", line 16, in <module>
    api.initialize()
  File "/api.py", line 83, in initialize
    api_root = bits[1]
IndexError: list index out of range
```

It would be great if an API key could be specified in the config so Flemmarr can still function even when `/initialize.js` is behind a login prompt.

**Comment by tigattack** [comment]
As a bare minimum fix, it would be good if the error could made a little more friendly so it's clear what the problem is 🙂
